# Copyright 2019 YugaByte, Inc. and Contributors
#
# Licensed under the Polyform Free Trial License 1.0.0 (the "License"); you
# may not use this file except in compliance with the License. You
# may obtain a copy of the License at
#
# https://github.com/YugaByte/yugabyte-db/blob/master/licenses/POLYFORM-FREE-TRIAL-LICENSE-1.0.0.txt

- name: Setup SSH | Create .ssh directory
  file:
    path: "{{ create_user.home_dir }}/.ssh"
    state: directory
    mode: 0700
    owner: "{{ create_user.name  }}"
    group: "{{ create_user.name  }}"

- block:
  - name: Setup SSH | Check if private key file exists
    stat:
      path: "{{ create_user.home_dir }}/.ssh/id_rsa"
    register: stat_result

  - name: Setup SSH | Install private key
    copy:
      content: "{{ ssh_config.id_rsa }}"
      dest: "{{ create_user.home_dir }}/.ssh/id_rsa"
      mode: 0600
      owner: "{{ create_user.name  }}"
      group: "{{ create_user.name  }}"
    when: not stat_result.stat.exists

  - name: Setup SSH | Install private key
    copy:
      content: "{{ ssh_config.id_rsa_pub }}"
      dest: "{{ create_user.home_dir }}/.ssh/id_rsa.pub"
      mode: 0600
      owner: "{{ create_user.name  }}"
      group: "{{ create_user.name  }}"
    when: not stat_result.stat.exists

- name: Setup SSH | Install authorized keys
  authorized_key:
    user: "{{ create_user.name  }}"
    key: "{{ item }}"
    state: present
    manage_dir: true
  with_items: "{{ ssh_config.authorized_keys }}"
  loop_control:
    label: "{{ create_user.name }}-keys"

- name: Setup SSH | Append the authorized keys to the sudo user
  authorized_key:
    user: "{{ ssh_config.sudo_user }}"
    key: "{{ ssh_config.authorized_keys }}"
