# Copyright 2019 YugaByte, Inc. and Contributors
#
# Licensed under the Polyform Free Trial License 1.0.0 (the "License"); you
# may not use this file except in compliance with the License. You
# may obtain a copy of the License at
#
# https://github.com/YugaByte/yugabyte-db/blob/master/licenses/POLYFORM-FREE-TRIAL-LICENSE-1.0.0.txt

- name: Setup SSH | Create .ssh directory
  file:
    path: "/home/{{ create_user.name  }}/.ssh"
    state: directory
    mode: 0700
    owner: "{{ create_user.name  }}"
    group: "{{ create_user.name  }}"

- name: Setup SSH | Install private key
  copy:
    content: "{{ ssh_config.id_rsa }}"
    dest: "/home/{{ user_name }}/.ssh/id_rsa"
    mode: 0600
    owner: "{{ create_user.name  }}"
    group: "{{ create_user.name  }}"

- name: Setup SSH | Install public key
  copy:
    content: "{{ ssh_config.id_rsa_pub }}"
    dest: "/home/{{ create_user.name  }}/.ssh/id_rsa.pub"
    mode: 0600
    owner: "{{ create_user.name  }}"
    group: "{{ create_user.name  }}"

- name: Setup SSH | Install authorized keys
  copy:
    content: "{{ ssh_config.authorized_keys }}"
    dest: "/home/{{ create_user.name  }}/.ssh/authorized_keys"
    mode: 0600
    owner: "{{ create_user.name  }}"
    group: "{{ create_user.name  }}"

- name: Setup SSH | Append the authorized keys to the sudo user
  authorized_key:
    user: "{{ ssh_config.sudo_user }}"
    key: "{{ ssh_config.authorized_keys }}"
