# Copyright 2019 YugaByte, Inc. and Contributors
#
# Licensed under the Polyform Free Trial License 1.0.0 (the "License"); you
# may not use this file except in compliance with the License. You
# may obtain a copy of the License at
#
# https://github.com/YugaByte/yugabyte-db/blob/master/licenses/POLYFORM-FREE-TRIAL-LICENSE-1.0.0.txt

dependencies:
  - role: server_base

  - role: mount_ephemeral_drives
    when: cloud_type != "onprem"

  - role: swamper
    prometheus_components:
      - node_exporter

  - role: create_user
    create_user:
      name: "{{ user_name }}"
      shell: "/bin/bash"
      comment: "{{ user_name }}"
      home_dir: "/home/{{ user_name }}"
    ssh_config:
      enabled: "{{ cluster_server_vault|default(False) }}"
      id_rsa: "{{ cluster_server_vault | get_value('id_rsa') }}"
      id_rsa_pub: "{{ cluster_server_vault | get_value('id_rsa_pub') }}"
      sudo_user: "{{ yb_server_ssh_user | default(omit) }}"
      authorized_keys: "{{ cluster_server_vault | get_value('authorized_keys') }}"
