version: 2
jobs:
  # For image tags, see:
  # https://circleci.com/docs/2.0/docker-image-tags.json
  ubuntu1804:
    docker:
      - image: circleci/buildpack-deps:18.04
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y \
              python-pip \
              uuid-dev \
              libbz2-dev \
              libreadline-dev \
              maven \
              cmake \
              rsync \
              flex \
              bison \
              ninja-build \
              python-dev \
              openjdk-8-jdk-headless
      - run: |
          export MAVEN_OPTS="--add-opens=java.base/java.nio=ALL-UNNAMED"
          export YB_SKIP_INITIAL_SYS_CATALOG_SNAPSHOT=1
          java -version && ./yb_build.sh --ninja -j 1
workflows:
  # See https://circleci.com/docs/2.0/workflows/
  version: 2
  build_yugabyte_db:
    jobs:
      - ubuntu1804
