# Copyright 2020 YugaByte, Inc. and Contributors
#
# Licensed under the Polyform Free Trial License 1.0.0 (the "License"); you
# may not use this file except in compliance with the License. You
# may obtain a copy of the License at
#
# https://github.com/YugaByte/yugabyte-db/blob/master/licenses/POLYFORM-FREE-TRIAL-LICENSE-1.0.0.txt

- block:
    - name: s3cmd | Copy setuptools from {{ package_path }}
      synchronize:
        src: "{{ package_path }}/setuptools-44.1.1"
        dest: "/usr"
      when: remote_package_path is not defined or remote_package_path == ''

    - name: s3cmd | Copy and unarchive setuptools from {{ package_path }}
      unarchive:
        src: "{{ package_path }}/setuptools-44.1.1.tar.gz"
        dest: "/usr"
        remote_src: "{{ is_remote }}"
      when: remote_package_path is defined and remote_package_path != ''

    - set_fact:
        python_magic_package_path: "/usr/python-magic-0.4.18"

    - name: s3cmd | Copy and unarchive python magic from {{ package_path }}
      unarchive:
        src: "{{ package_path }}/python-magic-0.4.18.tar.gz"
        dest: "/usr"
        creates: "{{ python_magic_package_path }}"
        remote_src: "{{ is_remote }}"

    - set_fact:
        python_dateutil_package_path: "/usr/python-dateutil-2.8.1"

    - name: s3cmd | Copy and unarchive dateutil from {{ package_path }}
      unarchive:
        src: "{{ package_path }}/python-dateutil-2.8.1.tar.gz"
        dest: "/usr"
        creates: "{{ python_dateutil_package_path }}"
        remote_src: "{{ is_remote }}"

    - set_fact:
        s3cmd_package_path: "/usr/{{ s3cmd_package_name }}"

    - name: s3cmd | Copy and unarchive {{ s3cmd_package }} from {{ package_path }}
      unarchive:
        src: "{{ package_path }}/{{ s3cmd_package }}"
        dest: "/usr"
        creates: "{{ s3cmd_package_path }}"
        remote_src: "{{ is_remote }}"

    - name: s3cmd | Install setuptools
      command: "chdir=/usr/setuptools-44.1.1 python setup.py install"

    - name: s3cmd | Install python magic
      command: "chdir={{ python_magic_package_path }} python setup.py install"

    - name: s3cmd | Build dateutil
      command: "chdir={{ python_dateutil_package_path }} python setup.py build"

    - name: s3cmd | Install dateutil
      command: "chdir={{ python_dateutil_package_path }} python setup.py install"

    - name: s3cmd | Install s3cmd
      command: "chdir={{ s3cmd_package_path }} python setup.py install"

    - name: s3cmd | Create symlinks to {{ bin_path }}
      file:
        src: "{{ s3cmd_package_path }}/s3cmd"
        path: "{{ bin_path }}/s3cmd"
        state: link
        force: yes
