# Copyright 2020 YugaByte, Inc. and Contributors
#
# Licensed under the Polyform Free Trial License 1.0.0 (the "License"); you
# may not use this file except in compliance with the License. You
# may obtain a copy of the License at
#
# https://github.com/YugaByte/yugabyte-db/blob/master/licenses/POLYFORM-FREE-TRIAL-LICENSE-1.0.0.txt

- block:
    - name: Copy setuptools from thirdparty
      synchronize:
        src: "{{ local_package_path }}/setuptools-44.1.1"
        dest: "/usr"

    - name: Install setuptools
      command: "chdir=/usr/setuptools-44.1.1 python setup.py install"

    - name: Copy and unarchive dateutil from thirdparty
      unarchive:
        src: "{{ local_package_path }}/python-dateutil-2.8.1.tar.gz"
        dest: "/usr"

    - name: Build dateutil
      command: "chdir=/usr/python-dateutil-2.8.1 python setup.py build"

    - name: Install dateutil
      command: "chdir=/usr/python-dateutil-2.8.1 python setup.py install"

    - name: Copy and unarchive {{ s3cmd_package }} from thirdparty
      unarchive:
        src: "{{ local_package_path }}/{{ s3cmd_package }}"
        dest: "/usr"

    - set_fact:
        s3cmd_package_path: "/usr/{{ s3cmd_package_name }}"

    - name: Run install script
      command: "chdir={{ s3cmd_package_path }} python setup.py install"

    - name: Create symlinks to {{ bin_path }}
      file:
        src: "{{ s3cmd_package_path }}/s3cmd"
        path: "{{ bin_path }}/s3cmd"
        state: link
        force: yes
