# Copyright 2020 YugaByte, Inc. and Contributors
#
# Licensed under the Polyform Free Trial License 1.0.0 (the "License"); you
# may not use this file except in compliance with the License. You
# may obtain a copy of the License at
#
# https://github.com/YugaByte/yugabyte-db/blob/master/licenses/POLYFORM-FREE-TRIAL-LICENSE-1.0.0.txt

- block:
    - name: Copy and unarchive {{ gcloud_package }} from thirdparty
      unarchive:
        src: "{{ local_package_path }}/{{ gcloud_package }}"
        dest: "/usr"

    - set_fact:
        gcloud_package_path: "/usr/{{ gcloud_package_name }}"

    - name: Run install script
      command: "{{ gcloud_package_path }}/install.sh --quiet --usage-reporting false  --command-completion true --override-components gsutil"

    - name: Create symlinks to {{ bin_path }}
      file:
        src: "{{ gcloud_package_path }}/bin/gsutil"
        path: "{{ bin_path }}/gsutil"
        state: link
        force: yes
