# Copyright 2020 YugaByte, Inc. and Contributors
#
# Licensed under the Polyform Free Trial License 1.0.0 (the "License"); you
# may not use this file except in compliance with the License. You
# may obtain a copy of the License at
#
# https://github.com/YugaByte/yugabyte-db/blob/master/licenses/POLYFORM-FREE-TRIAL-LICENSE-1.0.0.txt

- block:
    - name: azcopy | Download and install azcopy from {{ package_path }}
      unarchive:
        src: "{{ package_path }}/{{ azcopy_package }}"
        dest: "{{ bin_path }}"
        creates: "{{ bin_path }}/azcopy"
        remote_src: "{{ is_remote }}"
        mode: 0755
        exclude:
          - ThirdPartyNotice.txt
        extra_opts: [--strip-components=1] # Remove tarball directory from extracted path.
